### ISSUE TITLE
Link error in the superlink in README.md

### ISSUE THREAD

**Issue by Stevan0102** [nus-cs2103/website#143] opened 2016-01-01 07:34 UTC
The superlink in Released Version linked to the word "here" is now linked to http://www.comp.nus.edu.sg/~cs2103/trial, it happens to be a 404 Not Found, I think it can be changed to http://www.comp.nus.edu.sg/~cs2103/

**Comment by damithc** [comment] 2016-01-01 08:00
Duplicate of #95

**Closed by damithc** 2016-01-01 08:00 UTC
