### ISSUE TITLE
Empty contents under some subheadings

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#24] opened 2015-09-30 14:18 UTC
![2unnamed](https://cloud.githubusercontent.com/assets/8586080/10195618/20e08208-67c1-11e5-826f-2c2e270b2dfb.png)
These empty parts are confusing.
Students may wonder if it's just not loading.
Best would be to remove the arrow and click event?
Or at least some text to mention the lack of text.

**Comment by damithc** [comment] 2015-09-30 14:37
I'll be filling out these over time.

**Comment by acjh** [comment] 2016-12-07 14:54
Closing because the issue is no longer relevant.

**Closed by acjh** 2016-12-07 14:54 UTC
Labels: priority.medium, type.enhancement
